// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uleykptbosbenlvqeuvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsZXlrcHRib3NiZW5sdnFldXZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NzMzNzcsImV4cCI6MjA3MTE0OTM3N30.kCgfsmlbSk0d9CJKfSk8oLSBJpgPH5WnMGihnIHCrX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});